version: 2.1

commands:
  install_and_cache_node_dependencies:
    steps:
      - restore_cache:
            keys:
              - v2-deps-{{ checksum "package-lock.json" }}
              - v2-deps-
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: v2-deps-{{ checksum "package-lock.json" }}
          paths:
              - node_modules

executors:
  node_docker:
    docker: 
      - image: cimg/node:16.16.0

jobs:
  build:
    executor: node_docker
    steps:
      - checkout
      - install_and_cache_node_dependencies
      - run:
          command: |
            npm run build 

  test:
    executor: node_docker
    steps:
      - checkout
      - install_and_cache_node_dependencies
      - run:
          command: |
            npm run test-ci

  lint:
    executor: node_docker
    steps:
      - checkout
      - install_and_cache_node_dependencies
      - run:
          command: |
            npm run lint
            
workflows:
  build_test_deploy:
      jobs:
        - build  
        - lint
        - test   

# VS Code Extension Version: 1.0.2