version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          command: |
            npm install
      - run:
          command: |
            npm run build 

  test:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          command: |
            npm install
      - run:
          command: |
            npm run test-ci

  lint:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          command: |
            npm install
      - run:
          command: |
            npm run lint
            
workflows:
  build_test_deploy:
      jobs:
        - build  
        - lint
        - test   

# VS Code Extension Version: 1.0.2